DEFS += -D R_STRUCT_PTR=1

ifeq ($(GAME), Dragon Fantasy 1)
	DEFS = -D S_CALLTYPE=
	DEFS += -D STEAM_REMOTESTORAGE_VERSION='"STEAMREMOTESTORAGE_INTERFACE_VERSION012"'
endif

ifeq ($(GAME), Dragon Fantasy 2)
	DEFS = -D S_CLASSAPI='__attribute__((fastcall))'
	DEFS += -D STEAM_REMOTESTORAGE_VERSION='"STEAMREMOTESTORAGE_INTERFACE_VERSION012"'
endif

ifeq ($(GAME), Final Fantasy 4 After Years)
	DEFS = -D R_STRUCT_PTR=1
	DEFS += -D STEAM_APPS_VERSION='"STEAMAPPS_INTERFACE_VERSION005"'
	DEFS += -D STEAM_CLIENT_VERSION='"SteamClient012"'
	DEFS += -D STEAM_FRIENDS_VERSION='"SteamFriends013"'
	DEFS += -D STEAM_HTTP_VERSION='"STEAMHTTP_INTERFACE_VERSION002"'
	DEFS += -D STEAM_MATCHMAKINGSERVERS_VERSION='"SteamMatchMakingServers002"'
	DEFS += -D STEAM_MATCHMAKING_VERSION='"SteamMatchMaking009"'
	DEFS += -D STEAM_NETWORKING_VERSION='"SteamNetworking005"'
	DEFS += -D STEAM_REMOTESTORAGE_VERSION='"STEAMREMOTESTORAGE_INTERFACE_VERSION011"'
	DEFS += -D STEAM_SCREENSHOTS_VERSION='"STEAMSCREENSHOTS_INTERFACE_VERSION002"'
	DEFS += -D STEAM_UNIFIEDMESSAGES_VERSION='"STEAMUNIFIEDMESSAGES_INTERFACE_VERSION001"'
	DEFS += -D STEAM_USERSTATS_VERSION='"STEAMUSERSTATS_INTERFACE_VERSION011"'
	DEFS += -D STEAM_USER_VERSION='"SteamUser017"'
	DEFS += -D STEAM_UTILS_VERSION='"SteamUtils006"'
endif

ifeq ($(GAME), Final Fantasy 5)
	DEFS = -D R_STRUCT_PTR=0 -D STEAM_APP_ID='382890'
	DEFS += -D STEAM_APPLIST_VERSION='"STEAMAPPLIST_INTERFACE_VERSION001"'
	DEFS += -D STEAM_APPS_VERSION='"STEAMAPPS_INTERFACE_VERSION007"'
	DEFS += -D STEAM_CLIENT_VERSION='"SteamClient017"'
	DEFS += -D STEAM_FRIENDS_VERSION='"SteamFriends015"'
	DEFS += -D STEAM_HTMLSURFACE_VERSION='"STEAMHTMLSURFACE_INTERFACE_VERSION_003"'
	DEFS += -D STEAM_HTTP_VERSION='"STEAMHTTP_INTERFACE_VERSION002"'
	DEFS += -D STEAM_INVENTORY_VERSION='"STEAMINVENTORY_INTERFACE_V001"'
	DEFS += -D STEAM_MATCHMAKINGSERVERS_VERSION='"SteamMatchMakingServers002"'
	DEFS += -D STEAM_MATCHMAKING_VERSION='"SteamMatchMaking009"'
	DEFS += -D STEAM_MUSICREMOTE_VERSION='"STEAMMUSICREMOTE_INTERFACE_VERSION001"'
	DEFS += -D STEAM_MUSIC_VERSION='"STEAMMUSIC_INTERFACE_VERSION001"'
	DEFS += -D STEAM_NETWORKING_VERSION='"SteamNetworking005"'
	DEFS += -D STEAM_REMOTESTORAGE_VERSION='"STEAMREMOTESTORAGE_INTERFACE_VERSION012"'
	DEFS += -D STEAM_SCREENSHOTS_VERSION='"STEAMSCREENSHOTS_INTERFACE_VERSION002"'
	DEFS += -D STEAM_UGC_VERSION='"STEAMUGC_INTERFACE_VERSION005"'
	DEFS += -D STEAM_UNIFIEDMESSAGES_VERSION='"STEAMUNIFIEDMESSAGES_INTERFACE_VERSION001"'
	DEFS += -D STEAM_USERSTATS_VERSION='"STEAMUSERSTATS_INTERFACE_VERSION011"'
	DEFS += -D STEAM_USER_VERSION='"SteamUser018"'
	DEFS += -D STEAM_UTILS_VERSION='"SteamUtils007"'
	DEFS += -D STEAM_VIDEO_VERSION='"STEAMVIDEO_INTERFACE_V001"'
endif

ifeq ($(GAME), Final Fantasy 6)
	DEFS += -D STEAM_APPLIST_VERSION='"STEAMAPPLIST_INTERFACE_VERSION001"'
	DEFS += -D STEAM_APPS_VERSION='"STEAMAPPS_INTERFACE_VERSION007"'
	DEFS += -D STEAM_CLIENT_VERSION='"SteamClient017"'
	DEFS += -D STEAM_FRIENDS_VERSION='"SteamFriends015"'
	DEFS += -D STEAM_HTMLSURFACE_VERSION='"STEAMHTMLSURFACE_INTERFACE_VERSION_003"'
	DEFS += -D STEAM_HTTP_VERSION='"STEAMHTTP_INTERFACE_VERSION002"'
	DEFS += -D STEAM_INVENTORY_VERSION='"STEAMINVENTORY_INTERFACE_V001"'
	DEFS += -D STEAM_MATCHMAKINGSERVERS_VERSION='"SteamMatchMakingServers002"'
	DEFS += -D STEAM_MATCHMAKING_VERSION='"SteamMatchMaking009"'
	DEFS += -D STEAM_MUSICREMOTE_VERSION='"STEAMMUSICREMOTE_INTERFACE_VERSION001"'
	DEFS += -D STEAM_MUSIC_VERSION='"STEAMMUSIC_INTERFACE_VERSION001"'
	DEFS += -D STEAM_NETWORKING_VERSION='"SteamNetworking005"'
	DEFS += -D STEAM_REMOTESTORAGE_VERSION='"STEAMREMOTESTORAGE_INTERFACE_VERSION012"'
	DEFS += -D STEAM_SCREENSHOTS_VERSION='"STEAMSCREENSHOTS_INTERFACE_VERSION002"'
	DEFS += -D STEAM_UGC_VERSION='"STEAMUGC_INTERFACE_VERSION007"'
	DEFS += -D STEAM_UNIFIEDMESSAGES_VERSION='"STEAMUNIFIEDMESSAGES_INTERFACE_VERSION001"'
	DEFS += -D STEAM_USERSTATS_VERSION='"STEAMUSERSTATS_INTERFACE_VERSION011"'
	DEFS += -D STEAM_USER_VERSION='"SteamUser018"'
	DEFS += -D STEAM_UTILS_VERSION='"SteamUtils007"'
	DEFS += -D STEAM_VIDEO_VERSION='"STEAMVIDEO_INTERFACE_V001"'
endif

ifeq ($(GAME), Hyper Light Drifter)
	DEFS = -D R_STRUCT_PTR=0 -D S_CALLTYPE=
endif

ifeq ($(GAME), Pier Solar)
	DEFS = -D R_STRUCT_PTR=0
	DEFS += -D STEAM_REMOTESTORAGE_VERSION='"STEAMREMOTESTORAGE_INTERFACE_VERSION012"'
endif

ifeq ($(GAME), Disgaea 1)
	DEFS = -D R_STRUCT_PTR=1
	DEFS += -D STEAM_REMOTESTORAGE_VERSION='"STEAMREMOTESTORAGE_INTERFACE_VERSION012"'
endif

ifeq ($(GAME), Disgaea 2)
	DEFS = -D R_STRUCT_PTR=0
	DEFS += -D STEAM_APPLIST_VERSION='"STEAMAPPLIST_INTERFACE_VERSION001"'
	DEFS += -D STEAM_APPS_VERSION='"STEAMAPPS_INTERFACE_VERSION008"'
	DEFS += -D STEAM_CLIENT_VERSION='"SteamClient017"'
	DEFS += -D STEAM_CONTROLLER_VERSION='"SteamController003"'
	DEFS += -D STEAM_FRIENDS_VERSION='"SteamFriends015"'
	DEFS += -D STEAM_HTMLSURFACE_VERSION='"STEAMHTMLSURFACE_INTERFACE_VERSION_003"'
	DEFS += -D STEAM_HTTP_VERSION='"STEAMHTTP_INTERFACE_VERSION002"'
	DEFS += -D STEAM_INVENTORY_VERSION='"STEAMINVENTORY_INTERFACE_V001"'
	DEFS += -D STEAM_MATCHMAKINGSERVERS_VERSION='"SteamMatchMakingServers002"'
	DEFS += -D STEAM_MATCHMAKING_VERSION='"SteamMatchMaking009"'
	DEFS += -D STEAM_MUSICREMOTE_VERSION='"STEAMMUSICREMOTE_INTERFACE_VERSION001"'
	DEFS += -D STEAM_MUSIC_VERSION='"STEAMMUSIC_INTERFACE_VERSION001"'
	DEFS += -D STEAM_NETWORKING_VERSION='"SteamNetworking005"'
	DEFS += -D STEAM_REMOTESTORAGE_VERSION='"STEAMREMOTESTORAGE_INTERFACE_VERSION013"'
	DEFS += -D STEAM_SCREENSHOTS_VERSION='"STEAMSCREENSHOTS_INTERFACE_VERSION002"'
	DEFS += -D STEAM_UGC_VERSION='"STEAMUGC_INTERFACE_VERSION008"'
	DEFS += -D STEAM_UNIFIEDMESSAGES_VERSION='"STEAMUNIFIEDMESSAGES_INTERFACE_VERSION001"'
	DEFS += -D STEAM_USERSTATS_VERSION='"STEAMUSERSTATS_INTERFACE_VERSION011"'
	DEFS += -D STEAM_USER_VERSION='"SteamUser019"'
	DEFS += -D STEAM_UTILS_VERSION='"SteamUtils008"'
	DEFS += -D STEAM_VIDEO_VERSION='"STEAMVIDEO_INTERFACE_V001"'
endif

ifeq ($(GAME), Disgaea 4)
	DEFS = -D R_STRUCT_PTR=1
	DEFS += -D STEAM_REMOTESTORAGE_VERSION='"STEAMREMOTESTORAGE_INTERFACE_VERSION014"'
endif

ifeq ($(GAME), Disgaea 5)
	DEFS = -D R_STRUCT_PTR=1
	DEFS += -D STEAM_REMOTESTORAGE_VERSION='"STEAMREMOTESTORAGE_INTERFACE_VERSION014"'
endif

ifeq ($(GAME), Battle Chasers Nightwar)
	DEFS = -D R_STRUCT_PTR=0
	DEFS += -D STEAM_APPLIST_VERSION='"STEAMAPPLIST_INTERFACE_VERSION001"'
	DEFS += -D STEAM_APPS_VERSION='"STEAMAPPS_INTERFACE_VERSION007"'
	DEFS += -D STEAM_FRIENDS_VERSION='"SteamFriends015"'
	DEFS += -D STEAM_HTMLSURFACE_VERSION='"STEAMHTMLSURFACE_INTERFACE_VERSION_003"'
	DEFS += -D STEAM_HTTP_VERSION='"STEAMHTTP_INTERFACE_VERSION002"'
	DEFS += -D STEAM_INVENTORY_VERSION='"STEAMINVENTORY_INTERFACE_V001"'
	DEFS += -D STEAM_MATCHMAKINGSERVERS_VERSION='"SteamMatchMakingServers002"'
	DEFS += -D STEAM_MATCHMAKING_VERSION='"SteamMatchMaking009"'
	DEFS += -D STEAM_MUSICREMOTE_VERSION='"STEAMMUSICREMOTE_INTERFACE_VERSION001"'
	DEFS += -D STEAM_MUSIC_VERSION='"STEAMMUSIC_INTERFACE_VERSION001"'
	DEFS += -D STEAM_NETWORKING_VERSION='"SteamNetworking005"'
	DEFS += -D STEAM_REMOTESTORAGE_VERSION='"STEAMREMOTESTORAGE_INTERFACE_VERSION012"'
	DEFS += -D STEAM_SCREENSHOTS_VERSION='"STEAMSCREENSHOTS_INTERFACE_VERSION002"'
	DEFS += -D STEAM_UGC_VERSION='"STEAMUGC_INTERFACE_VERSION007"'
	DEFS += -D STEAM_UNIFIEDMESSAGES_VERSION='"STEAMUNIFIEDMESSAGES_INTERFACE_VERSION001"'
	DEFS += -D STEAM_USERSTATS_VERSION='"STEAMUSERSTATS_INTERFACE_VERSION011"'
	DEFS += -D STEAM_USER_VERSION='"SteamUser018"'
	DEFS += -D STEAM_UTILS_VERSION='"SteamUtils007"'
	DEFS += -D STEAM_VIDEO_VERSION='"STEAMVIDEO_INTERFACE_V001"'
endif

ifeq ($(GAME), Ys Seven)
	DEFS = -D R_STRUCT_PTR=0
	DEFS += -D STEAM_APPLIST_VERSION='"STEAMAPPLIST_INTERFACE_VERSION001"'
	DEFS += -D STEAM_APPS_VERSION='"STEAMAPPS_INTERFACE_VERSION008"'
	DEFS += -D STEAM_CLIENT_VERSION='"SteamClient017"'
	DEFS += -D STEAM_CONTROLLER_VERSION='"SteamController005"'
	DEFS += -D STEAM_FRIENDS_VERSION='"SteamFriends015"'
	DEFS += -D STEAM_HTMLSURFACE_VERSION='"STEAMHTMLSURFACE_INTERFACE_VERSION_003"'
	DEFS += -D STEAM_HTTP_VERSION='"STEAMHTTP_INTERFACE_VERSION002"'
	DEFS += -D STEAM_INVENTORY_VERSION='"STEAMINVENTORY_INTERFACE_V001"'
	DEFS += -D STEAM_MATCHMAKINGSERVERS_VERSION='"SteamMatchMakingServers002"'
	DEFS += -D STEAM_MATCHMAKING_VERSION='"SteamMatchMaking009"'
	DEFS += -D STEAM_MUSICREMOTE_VERSION='"STEAMMUSICREMOTE_INTERFACE_VERSION001"'
	DEFS += -D STEAM_MUSIC_VERSION='"STEAMMUSIC_INTERFACE_VERSION001"'
	DEFS += -D STEAM_NETWORKING_VERSION='"SteamNetworking005"'
	DEFS += -D STEAM_REMOTESTORAGE_VERSION='"STEAMREMOTESTORAGE_INTERFACE_VERSION014"'
	DEFS += -D STEAM_SCREENSHOTS_VERSION='"STEAMSCREENSHOTS_INTERFACE_VERSION003"'
	DEFS += -D STEAM_UGC_VERSION='"STEAMUGC_INTERFACE_VERSION009"'
	DEFS += -D STEAM_UNIFIEDMESSAGES_VERSION='"STEAMUNIFIEDMESSAGES_INTERFACE_VERSION001"'
	DEFS += -D STEAM_USERSTATS_VERSION='"STEAMUSERSTATS_INTERFACE_VERSION011"'
	DEFS += -D STEAM_USER_VERSION='"SteamUser019"'
	DEFS += -D STEAM_UTILS_VERSION='"SteamUtils008"'
	DEFS += -D STEAM_VIDEO_VERSION='"STEAMVIDEO_INTERFACE_V001"'	
endif

ifeq ($(GAME), CrossCode)
	DEFS += -D STEAM_CLIENT_VERSION='"SteamClient017"'
	DEFS += -D STEAM_CONTROLLER_VERSION='"SteamController006"'
	DEFS += -D STEAM_USER_VERSION='"SteamUser019"'
	DEFS += -D STEAM_UTILS_VERSION='"SteamUtils009"'
endif

DEFS += -D GAME="$(GAME)"

