#include "steam.h"

static void *vtable_ISteamMatchmaking009[] = {
    SteamAPI_ISteamMatchmaking_GetFavoriteGameCount,
    SteamAPI_ISteamMatchmaking_GetFavoriteGame,
    SteamAPI_ISteamMatchmaking_AddFavoriteGame,
    SteamAPI_ISteamMatchmaking_RemoveFavoriteGame,
    SteamAPI_ISteamMatchmaking_RequestLobbyList,
    SteamAPI_ISteamMatchmaking_AddRequestLobbyListStringFilter,
    SteamAPI_ISteamMatchmaking_AddRequestLobbyListNumericalFilter,
    SteamAPI_ISteamMatchmaking_AddRequestLobbyListNearValueFilter,
    SteamAPI_ISteamMatchmaking_AddRequestLobbyListFilterSlotsAvailable,
    SteamAPI_ISteamMatchmaking_AddRequestLobbyListDistanceFilter,
    SteamAPI_ISteamMatchmaking_AddRequestLobbyListResultCountFilter,
    SteamAPI_ISteamMatchmaking_AddRequestLobbyListCompatibleMembersFilter,
    SteamAPI_ISteamMatchmaking_GetLobbyByIndex,
    SteamAPI_ISteamMatchmaking_CreateLobby,
    SteamAPI_ISteamMatchmaking_JoinLobby,
    SteamAPI_ISteamMatchmaking_LeaveLobby,
    SteamAPI_ISteamMatchmaking_InviteUserToLobby,
    SteamAPI_ISteamMatchmaking_GetNumLobbyMembers,
    SteamAPI_ISteamMatchmaking_GetLobbyMemberByIndex,
    SteamAPI_ISteamMatchmaking_GetLobbyData,
    SteamAPI_ISteamMatchmaking_SetLobbyData,
    SteamAPI_ISteamMatchmaking_GetLobbyDataCount,
    SteamAPI_ISteamMatchmaking_GetLobbyDataByIndex,
    SteamAPI_ISteamMatchmaking_DeleteLobbyData,
    SteamAPI_ISteamMatchmaking_GetLobbyMemberData,
    SteamAPI_ISteamMatchmaking_SetLobbyMemberData,
    SteamAPI_ISteamMatchmaking_SendLobbyChatMsg,
    SteamAPI_ISteamMatchmaking_GetLobbyChatEntry,
    SteamAPI_ISteamMatchmaking_RequestLobbyData,
    SteamAPI_ISteamMatchmaking_SetLobbyGameServer,
    SteamAPI_ISteamMatchmaking_GetLobbyGameServer,
    SteamAPI_ISteamMatchmaking_SetLobbyMemberLimit,
    SteamAPI_ISteamMatchmaking_GetLobbyMemberLimit,
    SteamAPI_ISteamMatchmaking_SetLobbyType,
    SteamAPI_ISteamMatchmaking_SetLobbyJoinable,
    SteamAPI_ISteamMatchmaking_GetLobbyOwner,
    SteamAPI_ISteamMatchmaking_SetLobbyOwner,
    SteamAPI_ISteamMatchmaking_SetLinkedLobby,
};

VtableEntry vtable_ISteamMatchmaking[] = {
    {9, vtable_ISteamMatchmaking009, sizeof(vtable_ISteamMatchmaking009), 0},
    {0, NULL, 0, 0},
};
