#include "steam.h"

static void *vtable_ISteamUser017[] = {
    SteamAPI_ISteamUser_GetHSteamUser,
    SteamAPI_ISteamUser_BLoggedOn,
    SteamAPI_ISteamUser_GetSteamID,
    SteamAPI_ISteamUser_InitiateGameConnection,
    SteamAPI_ISteamUser_TerminateGameConnection,
    SteamAPI_ISteamUser_TrackAppUsageEvent,
    SteamAPI_ISteamUser_GetUserDataFolder,
    SteamAPI_ISteamUser_StartVoiceRecording,
    SteamAPI_ISteamUser_StopVoiceRecording,
    SteamAPI_ISteamUser_GetAvailableVoice,
    SteamAPI_ISteamUser_GetVoice,
    SteamAPI_ISteamUser_DecompressVoice,
    SteamAPI_ISteamUser_GetVoiceOptimalSampleRate,
    SteamAPI_ISteamUser_GetAuthSessionTicket,
    SteamAPI_ISteamUser_BeginAuthSession,
    SteamAPI_ISteamUser_EndAuthSession,
    SteamAPI_ISteamUser_CancelAuthTicket,
    SteamAPI_ISteamUser_UserHasLicenseForApp,
    SteamAPI_ISteamUser_BIsBehindNAT,
    SteamAPI_ISteamUser_RequestEncryptedAppTicket,
    SteamAPI_ISteamUser_GetEncryptedAppTicket,
    SteamAPI_ISteamUser_GetGameBadgeLevel,
    SteamAPI_ISteamUser_GetPlayerSteamLevel,
};

static void *vtable_ISteamUser018[] = {
    SteamAPI_ISteamUser_GetHSteamUser,
    SteamAPI_ISteamUser_BLoggedOn,
    SteamAPI_ISteamUser_GetSteamID,
    SteamAPI_ISteamUser_InitiateGameConnection,
    SteamAPI_ISteamUser_TerminateGameConnection,
    SteamAPI_ISteamUser_TrackAppUsageEvent,
    SteamAPI_ISteamUser_GetUserDataFolder,
    SteamAPI_ISteamUser_StartVoiceRecording,
    SteamAPI_ISteamUser_StopVoiceRecording,
    SteamAPI_ISteamUser_GetAvailableVoice,
    SteamAPI_ISteamUser_GetVoice,
    SteamAPI_ISteamUser_DecompressVoice,
    SteamAPI_ISteamUser_GetVoiceOptimalSampleRate,
    SteamAPI_ISteamUser_GetAuthSessionTicket,
    SteamAPI_ISteamUser_BeginAuthSession,
    SteamAPI_ISteamUser_EndAuthSession,
    SteamAPI_ISteamUser_CancelAuthTicket,
    SteamAPI_ISteamUser_UserHasLicenseForApp,
    SteamAPI_ISteamUser_BIsBehindNAT,
    SteamAPI_ISteamUser_RequestEncryptedAppTicket,
    SteamAPI_ISteamUser_GetEncryptedAppTicket,
    SteamAPI_ISteamUser_GetGameBadgeLevel,
    SteamAPI_ISteamUser_GetPlayerSteamLevel,
    SteamAPI_ISteamUser_RequestStoreAuthURL,
};

static void *vtable_ISteamUser019[] = {
    SteamAPI_ISteamUser_GetHSteamUser,
    SteamAPI_ISteamUser_BLoggedOn,
    SteamAPI_ISteamUser_GetSteamID,
    SteamAPI_ISteamUser_InitiateGameConnection,
    SteamAPI_ISteamUser_TerminateGameConnection,
    SteamAPI_ISteamUser_TrackAppUsageEvent,
    SteamAPI_ISteamUser_GetUserDataFolder,
    SteamAPI_ISteamUser_StartVoiceRecording,
    SteamAPI_ISteamUser_StopVoiceRecording,
    SteamAPI_ISteamUser_GetAvailableVoice,
    SteamAPI_ISteamUser_GetVoice,
    SteamAPI_ISteamUser_DecompressVoice,
    SteamAPI_ISteamUser_GetVoiceOptimalSampleRate,
    SteamAPI_ISteamUser_GetAuthSessionTicket,
    SteamAPI_ISteamUser_BeginAuthSession,
    SteamAPI_ISteamUser_EndAuthSession,
    SteamAPI_ISteamUser_CancelAuthTicket,
    SteamAPI_ISteamUser_UserHasLicenseForApp,
    SteamAPI_ISteamUser_BIsBehindNAT,
    SteamAPI_ISteamUser_RequestEncryptedAppTicket,
    SteamAPI_ISteamUser_GetEncryptedAppTicket,
    SteamAPI_ISteamUser_GetGameBadgeLevel,
    SteamAPI_ISteamUser_GetPlayerSteamLevel,
    SteamAPI_ISteamUser_RequestStoreAuthURL,
    SteamAPI_ISteamUser_BIsPhoneVerified,
    SteamAPI_ISteamUser_BIsTwoFactorEnabled,
    SteamAPI_ISteamUser_BIsPhoneIdentifying,
    SteamAPI_ISteamUser_BIsPhoneRequiringVerification,
};

static void *vtable_ISteamUser020[] = {
    SteamAPI_ISteamUser_GetHSteamUser,
    SteamAPI_ISteamUser_BLoggedOn,
    SteamAPI_ISteamUser_GetSteamID,
    SteamAPI_ISteamUser_InitiateGameConnection,
    SteamAPI_ISteamUser_TerminateGameConnection,
    SteamAPI_ISteamUser_TrackAppUsageEvent,
    SteamAPI_ISteamUser_GetUserDataFolder,
    SteamAPI_ISteamUser_StartVoiceRecording,
    SteamAPI_ISteamUser_StopVoiceRecording,
    SteamAPI_ISteamUser_GetAvailableVoice,
    SteamAPI_ISteamUser_GetVoice,
    SteamAPI_ISteamUser_DecompressVoice,
    SteamAPI_ISteamUser_GetVoiceOptimalSampleRate,
    SteamAPI_ISteamUser_GetAuthSessionTicket,
    SteamAPI_ISteamUser_BeginAuthSession,
    SteamAPI_ISteamUser_EndAuthSession,
    SteamAPI_ISteamUser_CancelAuthTicket,
    SteamAPI_ISteamUser_UserHasLicenseForApp,
    SteamAPI_ISteamUser_BIsBehindNAT,
    SteamAPI_ISteamUser_RequestEncryptedAppTicket,
    SteamAPI_ISteamUser_GetEncryptedAppTicket,
    SteamAPI_ISteamUser_GetGameBadgeLevel,
    SteamAPI_ISteamUser_GetPlayerSteamLevel,
    SteamAPI_ISteamUser_RequestStoreAuthURL,
    SteamAPI_ISteamUser_BIsPhoneVerified,
    SteamAPI_ISteamUser_BIsTwoFactorEnabled,
    SteamAPI_ISteamUser_BIsPhoneIdentifying,
    SteamAPI_ISteamUser_BIsPhoneRequiringVerification,
    SteamAPI_ISteamUser_GetMarketEligibility,
    SteamAPI_ISteamUser_GetDurationControl,
};

static void *vtable_ISteamUser021[] = {
    SteamAPI_ISteamUser_GetHSteamUser,
    SteamAPI_ISteamUser_BLoggedOn,
    SteamAPI_ISteamUser_GetSteamID,
    SteamAPI_ISteamUser_InitiateGameConnection,
    SteamAPI_ISteamUser_TerminateGameConnection,
    SteamAPI_ISteamUser_TrackAppUsageEvent,
    SteamAPI_ISteamUser_GetUserDataFolder,
    SteamAPI_ISteamUser_StartVoiceRecording,
    SteamAPI_ISteamUser_StopVoiceRecording,
    SteamAPI_ISteamUser_GetAvailableVoice,
    SteamAPI_ISteamUser_GetVoice,
    SteamAPI_ISteamUser_DecompressVoice,
    SteamAPI_ISteamUser_GetVoiceOptimalSampleRate,
    SteamAPI_ISteamUser_GetAuthSessionTicket,
    SteamAPI_ISteamUser_BeginAuthSession,
    SteamAPI_ISteamUser_EndAuthSession,
    SteamAPI_ISteamUser_CancelAuthTicket,
    SteamAPI_ISteamUser_UserHasLicenseForApp,
    SteamAPI_ISteamUser_BIsBehindNAT,
    SteamAPI_ISteamUser_RequestEncryptedAppTicket,
    SteamAPI_ISteamUser_GetEncryptedAppTicket,
    SteamAPI_ISteamUser_GetGameBadgeLevel,
    SteamAPI_ISteamUser_GetPlayerSteamLevel,
    SteamAPI_ISteamUser_RequestStoreAuthURL,
    SteamAPI_ISteamUser_BIsPhoneVerified,
    SteamAPI_ISteamUser_BIsTwoFactorEnabled,
    SteamAPI_ISteamUser_BIsPhoneIdentifying,
    SteamAPI_ISteamUser_BIsPhoneRequiringVerification,
    SteamAPI_ISteamUser_GetMarketEligibility,
    SteamAPI_ISteamUser_GetDurationControl,
    SteamAPI_ISteamUser_BSetDurationControlOnlineState,
};

VtableEntry vtable_ISteamUser[] = {
    {17, vtable_ISteamUser017, sizeof(vtable_ISteamUser017), 0},
    {18, vtable_ISteamUser018, sizeof(vtable_ISteamUser018), 0},
    {19, vtable_ISteamUser019, sizeof(vtable_ISteamUser019), 0},
    {20, vtable_ISteamUser020, sizeof(vtable_ISteamUser020), 0},
    {21, vtable_ISteamUser021, sizeof(vtable_ISteamUser021), 0},
    {0, NULL, 0, 0},
};

void *SteamAPI_SteamUser_v021 = &ctx.user;
