#include "steam.h"

static void *vtable_ISteamInput002[] = {
    SteamAPI_ISteamInput_Init,
    SteamAPI_ISteamInput_Shutdown,
    SteamAPI_ISteamInput_RunFrame,
    SteamAPI_ISteamInput_GetConnectedControllers,
    SteamAPI_ISteamInput_GetActionSetHandle,
    SteamAPI_ISteamInput_ActivateActionSet,
    SteamAPI_ISteamInput_GetCurrentActionSet,
    SteamAPI_ISteamInput_ActivateActionSetLayer,
    SteamAPI_ISteamInput_DeactivateActionSetLayer,
    SteamAPI_ISteamInput_DeactivateAllActionSetLayers,
    SteamAPI_ISteamInput_GetActiveActionSetLayers,
    SteamAPI_ISteamInput_GetDigitalActionHandle,
    SteamAPI_ISteamInput_GetDigitalActionData,
    SteamAPI_ISteamInput_GetDigitalActionOrigins,
    SteamAPI_ISteamInput_GetAnalogActionHandle,
    SteamAPI_ISteamInput_GetAnalogActionData,
    SteamAPI_ISteamInput_GetAnalogActionOrigins,
    SteamAPI_ISteamInput_GetGlyphForActionOrigin,
    SteamAPI_ISteamInput_GetStringForActionOrigin,
    SteamAPI_ISteamInput_StopAnalogActionMomentum,
    SteamAPI_ISteamInput_GetMotionData,
    SteamAPI_ISteamInput_TriggerVibration,
    SteamAPI_ISteamInput_SetLEDColor,
    SteamAPI_ISteamInput_TriggerHapticPulse,
    SteamAPI_ISteamInput_TriggerRepeatedHapticPulse,
    SteamAPI_ISteamInput_ShowBindingPanel,
    SteamAPI_ISteamInput_GetInputTypeForHandle,
    SteamAPI_ISteamInput_GetControllerForGamepadIndex,
    SteamAPI_ISteamInput_GetGamepadIndexForController,
    SteamAPI_ISteamInput_GetStringForXboxOrigin,
    SteamAPI_ISteamInput_GetGlyphForXboxOrigin,
    SteamAPI_ISteamInput_GetActionOriginFromXboxOrigin,
    SteamAPI_ISteamInput_TranslateActionOrigin,
    SteamAPI_ISteamInput_GetDeviceBindingRevision,
    SteamAPI_ISteamInput_GetRemotePlaySessionID,
};

static void *vtable_ISteamInput005[] = {
    SteamAPI_ISteamInput_Init,
    SteamAPI_ISteamInput_Shutdown,
    SteamAPI_ISteamInput_SetInputActionManifestFilePath,
    SteamAPI_ISteamInput_RunFrame,
    SteamAPI_ISteamInput_BWaitForData,
    SteamAPI_ISteamInput_BNewDataAvailable,
    SteamAPI_ISteamInput_GetConnectedControllers,
    SteamAPI_ISteamInput_EnableDeviceCallbacks,
    SteamAPI_ISteamInput_EnableActionEventCallbacks,
    SteamAPI_ISteamInput_GetActionSetHandle,
    SteamAPI_ISteamInput_ActivateActionSet,
    SteamAPI_ISteamInput_GetCurrentActionSet,
    SteamAPI_ISteamInput_ActivateActionSetLayer,
    SteamAPI_ISteamInput_DeactivateActionSetLayer,
    SteamAPI_ISteamInput_DeactivateAllActionSetLayers,
    SteamAPI_ISteamInput_GetActiveActionSetLayers,
    SteamAPI_ISteamInput_GetDigitalActionHandle,
    SteamAPI_ISteamInput_GetDigitalActionData,
    SteamAPI_ISteamInput_GetDigitalActionOrigins,
    SteamAPI_ISteamInput_GetStringForDigitalActionName,
    SteamAPI_ISteamInput_GetAnalogActionHandle,
    SteamAPI_ISteamInput_GetAnalogActionData,
    SteamAPI_ISteamInput_GetAnalogActionOrigins,
    SteamAPI_ISteamInput_GetGlyphPNGForActionOrigin,
    SteamAPI_ISteamInput_GetGlyphSVGForActionOrigin,
    SteamAPI_ISteamInput_GetGlyphForActionOrigin_Legacy,
    SteamAPI_ISteamInput_GetStringForActionOrigin,
    SteamAPI_ISteamInput_GetStringForAnalogActionName,
    SteamAPI_ISteamInput_StopAnalogActionMomentum,
    SteamAPI_ISteamInput_GetMotionData,
    SteamAPI_ISteamInput_TriggerVibration,
    SteamAPI_ISteamInput_TriggerVibrationExtended,
    SteamAPI_ISteamInput_TriggerSimpleHapticEvent,
    SteamAPI_ISteamInput_SetLEDColor,
    SteamAPI_ISteamInput_Legacy_TriggerHapticPulse,
    SteamAPI_ISteamInput_Legacy_TriggerRepeatedHapticPulse,
    SteamAPI_ISteamInput_ShowBindingPanel,
    SteamAPI_ISteamInput_GetInputTypeForHandle,
    SteamAPI_ISteamInput_GetControllerForGamepadIndex,
    SteamAPI_ISteamInput_GetGamepadIndexForController,
    SteamAPI_ISteamInput_GetStringForXboxOrigin,
    SteamAPI_ISteamInput_GetGlyphForXboxOrigin,
    SteamAPI_ISteamInput_GetActionOriginFromXboxOrigin,
    SteamAPI_ISteamInput_TranslateActionOrigin,
    SteamAPI_ISteamInput_GetDeviceBindingRevision,
    SteamAPI_ISteamInput_GetRemotePlaySessionID,
    SteamAPI_ISteamInput_GetSessionInputConfigurationSettings,
};

VtableEntry vtable_ISteamInput[] = {
    {2, vtable_ISteamInput002, sizeof(vtable_ISteamInput002), 0},
    {5, vtable_ISteamInput005, sizeof(vtable_ISteamInput005), 0},
    {0, NULL, 0, 0},
};