#include "steam.h"

static void *vtable_ISteamApps005[] = {
    SteamAPI_ISteamApps_BIsSubscribed,
    SteamAPI_ISteamApps_BIsLowViolence,
    SteamAPI_ISteamApps_BIsCybercafe,
    SteamAPI_ISteamApps_BIsVACBanned,
    SteamAPI_ISteamApps_GetCurrentGameLanguage,
    SteamAPI_ISteamApps_GetAvailableGameLanguages,
    SteamAPI_ISteamApps_BIsSubscribedApp,
    SteamAPI_ISteamApps_BIsDlcInstalled,
    SteamAPI_ISteamApps_GetEarliestPurchaseUnixTime,
    SteamAPI_ISteamApps_BIsSubscribedFromFreeWeekend,
    SteamAPI_ISteamApps_GetDLCCount,
    SteamAPI_ISteamApps_BGetDLCDataByIndex,
    SteamAPI_ISteamApps_InstallDLC,
    SteamAPI_ISteamApps_UninstallDLC,
    SteamAPI_ISteamApps_RequestAppProofOfPurchaseKey,
    SteamAPI_ISteamApps_GetCurrentBetaName,
    SteamAPI_ISteamApps_MarkContentCorrupt,
    SteamAPI_ISteamApps_GetInstalledDepots,
    SteamAPI_ISteamApps_GetAppInstallDir,
    SteamAPI_ISteamApps_BIsAppInstalled,
};

static void *vtable_ISteamApps006[] = {
    SteamAPI_ISteamApps_BIsSubscribed,
    SteamAPI_ISteamApps_BIsLowViolence,
    SteamAPI_ISteamApps_BIsCybercafe,
    SteamAPI_ISteamApps_BIsVACBanned,
    SteamAPI_ISteamApps_GetCurrentGameLanguage,
    SteamAPI_ISteamApps_GetAvailableGameLanguages,
    SteamAPI_ISteamApps_BIsSubscribedApp,
    SteamAPI_ISteamApps_BIsDlcInstalled,
    SteamAPI_ISteamApps_GetEarliestPurchaseUnixTime,
    SteamAPI_ISteamApps_BIsSubscribedFromFreeWeekend,
    SteamAPI_ISteamApps_GetDLCCount,
    SteamAPI_ISteamApps_BGetDLCDataByIndex,
    SteamAPI_ISteamApps_InstallDLC,
    SteamAPI_ISteamApps_UninstallDLC,
    SteamAPI_ISteamApps_RequestAppProofOfPurchaseKey,
    SteamAPI_ISteamApps_GetCurrentBetaName,
    SteamAPI_ISteamApps_MarkContentCorrupt,
    SteamAPI_ISteamApps_GetInstalledDepots,
    SteamAPI_ISteamApps_GetAppInstallDir,
    SteamAPI_ISteamApps_BIsAppInstalled,
    SteamAPI_ISteamApps_GetAppOwner,
    SteamAPI_ISteamApps_GetLaunchQueryParam,
};

static void *vtable_ISteamApps007[] = {
    SteamAPI_ISteamApps_BIsSubscribed,
    SteamAPI_ISteamApps_BIsLowViolence,
    SteamAPI_ISteamApps_BIsCybercafe,
    SteamAPI_ISteamApps_BIsVACBanned,
    SteamAPI_ISteamApps_GetCurrentGameLanguage,
    SteamAPI_ISteamApps_GetAvailableGameLanguages,
    SteamAPI_ISteamApps_BIsSubscribedApp,
    SteamAPI_ISteamApps_BIsDlcInstalled,
    SteamAPI_ISteamApps_GetEarliestPurchaseUnixTime,
    SteamAPI_ISteamApps_BIsSubscribedFromFreeWeekend,
    SteamAPI_ISteamApps_GetDLCCount,
    SteamAPI_ISteamApps_BGetDLCDataByIndex,
    SteamAPI_ISteamApps_InstallDLC,
    SteamAPI_ISteamApps_UninstallDLC,
    SteamAPI_ISteamApps_RequestAppProofOfPurchaseKey,
    SteamAPI_ISteamApps_GetCurrentBetaName,
    SteamAPI_ISteamApps_MarkContentCorrupt,
    SteamAPI_ISteamApps_GetInstalledDepots,
    SteamAPI_ISteamApps_GetAppInstallDir,
    SteamAPI_ISteamApps_BIsAppInstalled,
    SteamAPI_ISteamApps_GetAppOwner,
    SteamAPI_ISteamApps_GetLaunchQueryParam,
    SteamAPI_ISteamApps_GetDlcDownloadProgress,
    SteamAPI_ISteamApps_GetAppBuildId,
};

static void *vtable_ISteamApps008[] = {
    SteamAPI_ISteamApps_BIsSubscribed,
    SteamAPI_ISteamApps_BIsLowViolence,
    SteamAPI_ISteamApps_BIsCybercafe,
    SteamAPI_ISteamApps_BIsVACBanned,
    SteamAPI_ISteamApps_GetCurrentGameLanguage,
    SteamAPI_ISteamApps_GetAvailableGameLanguages,
    SteamAPI_ISteamApps_BIsSubscribedApp,
    SteamAPI_ISteamApps_BIsDlcInstalled,
    SteamAPI_ISteamApps_GetEarliestPurchaseUnixTime,
    SteamAPI_ISteamApps_BIsSubscribedFromFreeWeekend,
    SteamAPI_ISteamApps_GetDLCCount,
    SteamAPI_ISteamApps_BGetDLCDataByIndex,
    SteamAPI_ISteamApps_InstallDLC,
    SteamAPI_ISteamApps_UninstallDLC,
    SteamAPI_ISteamApps_RequestAppProofOfPurchaseKey,
    SteamAPI_ISteamApps_GetCurrentBetaName,
    SteamAPI_ISteamApps_MarkContentCorrupt,
    SteamAPI_ISteamApps_GetInstalledDepots,
    SteamAPI_ISteamApps_GetAppInstallDir,
    SteamAPI_ISteamApps_BIsAppInstalled,
    SteamAPI_ISteamApps_GetAppOwner,
    SteamAPI_ISteamApps_GetLaunchQueryParam,
    SteamAPI_ISteamApps_GetDlcDownloadProgress,
    SteamAPI_ISteamApps_GetAppBuildId,
    SteamAPI_ISteamApps_RequestAllProofOfPurchaseKeys,
    SteamAPI_ISteamApps_GetFileDetails,
    SteamAPI_ISteamApps_GetLaunchCommandLine,
    SteamAPI_ISteamApps_BIsSubscribedFromFamilySharing,
    SteamAPI_ISteamApps_BIsTimedTrial,
};

VtableEntry vtable_ISteamApps[] = {
    {5, vtable_ISteamApps005, sizeof(vtable_ISteamApps005), 0},
    {6, vtable_ISteamApps006, sizeof(vtable_ISteamApps006), 0},
    {7, vtable_ISteamApps007, sizeof(vtable_ISteamApps007), 0},
    {8, vtable_ISteamApps008, sizeof(vtable_ISteamApps008), 0},
    {0, NULL, 0, 0},
};