#include "steam.h"

static void *vtable_ISteamInventory001[] = {
    SteamAPI_ISteamInventory_GetResultStatus,
    SteamAPI_ISteamInventory_GetResultItems,
    SteamAPI_ISteamInventory_GetResultTimestamp,
    SteamAPI_ISteamInventory_CheckResultSteamID,
    SteamAPI_ISteamInventory_DestroyResult,
    SteamAPI_ISteamInventory_GetAllItems,
    SteamAPI_ISteamInventory_GetItemsByID,
    SteamAPI_ISteamInventory_SerializeResult,
    SteamAPI_ISteamInventory_DeserializeResult,
    SteamAPI_ISteamInventory_GenerateItems,
    SteamAPI_ISteamInventory_GrantPromoItems,
    SteamAPI_ISteamInventory_AddPromoItem,
    SteamAPI_ISteamInventory_AddPromoItems,
    SteamAPI_ISteamInventory_ConsumeItem,
    SteamAPI_ISteamInventory_ExchangeItems,
    SteamAPI_ISteamInventory_TransferItemQuantity,
    SteamAPI_ISteamInventory_SendItemDropHeartbeat,
    SteamAPI_ISteamInventory_TriggerItemDrop,
    SteamAPI_ISteamInventory_TradeItems,
    SteamAPI_ISteamInventory_LoadItemDefinitions,
    SteamAPI_ISteamInventory_GetItemDefinitionIDs,
    SteamAPI_ISteamInventory_GetItemDefinitionProperty,
    SteamAPI_ISteamInventory_RequestEligiblePromoItemDefinitionsIDs,
    SteamAPI_ISteamInventory_GetEligiblePromoItemDefinitionIDs,
};

static void *vtable_ISteamInventory002[] = {
    SteamAPI_ISteamInventory_GetResultStatus,
    SteamAPI_ISteamInventory_GetResultItems,
    SteamAPI_ISteamInventory_GetResultTimestamp,
    SteamAPI_ISteamInventory_CheckResultSteamID,
    SteamAPI_ISteamInventory_DestroyResult,
    SteamAPI_ISteamInventory_GetAllItems,
    SteamAPI_ISteamInventory_GetItemsByID,
    SteamAPI_ISteamInventory_SerializeResult,
    SteamAPI_ISteamInventory_DeserializeResult,
    SteamAPI_ISteamInventory_GenerateItems,
    SteamAPI_ISteamInventory_GrantPromoItems,
    SteamAPI_ISteamInventory_AddPromoItem,
    SteamAPI_ISteamInventory_AddPromoItems,
    SteamAPI_ISteamInventory_ConsumeItem,
    SteamAPI_ISteamInventory_ExchangeItems,
    SteamAPI_ISteamInventory_TransferItemQuantity,
    SteamAPI_ISteamInventory_SendItemDropHeartbeat,
    SteamAPI_ISteamInventory_TriggerItemDrop,
    SteamAPI_ISteamInventory_TradeItems,
    SteamAPI_ISteamInventory_LoadItemDefinitions,
    SteamAPI_ISteamInventory_GetItemDefinitionIDs,
    SteamAPI_ISteamInventory_GetItemDefinitionProperty,
    SteamAPI_ISteamInventory_RequestEligiblePromoItemDefinitionsIDs,
    SteamAPI_ISteamInventory_GetEligiblePromoItemDefinitionIDs,
    SteamAPI_ISteamInventory_StartPurchase,
    SteamAPI_ISteamInventory_RequestPrices,
    SteamAPI_ISteamInventory_GetNumItemsWithPrices,
    SteamAPI_ISteamInventory_GetItemsWithPrices,
    SteamAPI_ISteamInventory_GetItemPrice,
    SteamAPI_ISteamInventory_StartUpdateProperties,
    SteamAPI_ISteamInventory_RemoveProperty,
    SteamAPI_ISteamInventory_SetPropertyString,
    SteamAPI_ISteamInventory_SetPropertyBool,
    SteamAPI_ISteamInventory_SetPropertyInt64,
    SteamAPI_ISteamInventory_SetPropertyFloat,
    SteamAPI_ISteamInventory_SubmitUpdateProperties,
};

static void *vtable_ISteamInventory003[] = {
    SteamAPI_ISteamInventory_GetResultStatus,
    SteamAPI_ISteamInventory_GetResultItems,
    SteamAPI_ISteamInventory_GetResultItemProperty,
    SteamAPI_ISteamInventory_GetResultTimestamp,
    SteamAPI_ISteamInventory_CheckResultSteamID,
    SteamAPI_ISteamInventory_DestroyResult,
    SteamAPI_ISteamInventory_GetAllItems,
    SteamAPI_ISteamInventory_GetItemsByID,
    SteamAPI_ISteamInventory_SerializeResult,
    SteamAPI_ISteamInventory_DeserializeResult,
    SteamAPI_ISteamInventory_GenerateItems,
    SteamAPI_ISteamInventory_GrantPromoItems,
    SteamAPI_ISteamInventory_AddPromoItem,
    SteamAPI_ISteamInventory_AddPromoItems,
    SteamAPI_ISteamInventory_ConsumeItem,
    SteamAPI_ISteamInventory_ExchangeItems,
    SteamAPI_ISteamInventory_TransferItemQuantity,
    SteamAPI_ISteamInventory_SendItemDropHeartbeat,
    SteamAPI_ISteamInventory_TriggerItemDrop,
    SteamAPI_ISteamInventory_TradeItems,
    SteamAPI_ISteamInventory_LoadItemDefinitions,
    SteamAPI_ISteamInventory_GetItemDefinitionIDs,
    SteamAPI_ISteamInventory_GetItemDefinitionProperty,
    SteamAPI_ISteamInventory_RequestEligiblePromoItemDefinitionsIDs,
    SteamAPI_ISteamInventory_GetEligiblePromoItemDefinitionIDs,
    SteamAPI_ISteamInventory_StartPurchase,
    SteamAPI_ISteamInventory_RequestPrices,
    SteamAPI_ISteamInventory_GetNumItemsWithPrices,
    SteamAPI_ISteamInventory_GetItemsWithPrices,
    SteamAPI_ISteamInventory_GetItemPrice,
    SteamAPI_ISteamInventory_StartUpdateProperties,
    SteamAPI_ISteamInventory_RemoveProperty,
    SteamAPI_ISteamInventory_SetPropertyString,
    SteamAPI_ISteamInventory_SetPropertyBool,
    SteamAPI_ISteamInventory_SetPropertyInt64,
    SteamAPI_ISteamInventory_SetPropertyFloat,
    SteamAPI_ISteamInventory_SubmitUpdateProperties,
    SteamAPI_ISteamInventory_InspectItem,
};

VtableEntry vtable_ISteamInventory[] = {
    {1, vtable_ISteamInventory001, sizeof(vtable_ISteamInventory001), 0},
    {2, vtable_ISteamInventory002, sizeof(vtable_ISteamInventory002), 0},
    {3, vtable_ISteamInventory003, sizeof(vtable_ISteamInventory003), 0},
    {0, NULL, 0, 0},
};