#include "steam.h"

static void *vtable_ISteamHTMLSurface002[] = {
    SteamAPI_ISteamHTMLSurface_Init,
    SteamAPI_ISteamHTMLSurface_Shutdown,
    SteamAPI_ISteamHTMLSurface_CreateBrowser,
    SteamAPI_ISteamHTMLSurface_RemoveBrowser,
    SteamAPI_ISteamHTMLSurface_LoadURL,
    SteamAPI_ISteamHTMLSurface_SetSize,
    SteamAPI_ISteamHTMLSurface_StopLoad,
    SteamAPI_ISteamHTMLSurface_Reload,
    SteamAPI_ISteamHTMLSurface_GoBack,
    SteamAPI_ISteamHTMLSurface_GoForward,
    SteamAPI_ISteamHTMLSurface_AddHeader,
    SteamAPI_ISteamHTMLSurface_ExecuteJavascript,
    SteamAPI_ISteamHTMLSurface_MouseUp,
    SteamAPI_ISteamHTMLSurface_MouseDown,
    SteamAPI_ISteamHTMLSurface_MouseDoubleClick,
    SteamAPI_ISteamHTMLSurface_MouseMove,
    SteamAPI_ISteamHTMLSurface_MouseWheel,
    SteamAPI_ISteamHTMLSurface_KeyDown,
    SteamAPI_ISteamHTMLSurface_KeyUp,
    SteamAPI_ISteamHTMLSurface_KeyChar,
    SteamAPI_ISteamHTMLSurface_SetHorizontalScroll,
    SteamAPI_ISteamHTMLSurface_SetVerticalScroll,
    SteamAPI_ISteamHTMLSurface_SetKeyFocus,
    SteamAPI_ISteamHTMLSurface_ViewSource,
    SteamAPI_ISteamHTMLSurface_CopyToClipboard,
    SteamAPI_ISteamHTMLSurface_PasteFromClipboard,
    SteamAPI_ISteamHTMLSurface_Find,
    SteamAPI_ISteamHTMLSurface_StopFind,
    SteamAPI_ISteamHTMLSurface_GetLinkAtPosition,
    SteamAPI_ISteamHTMLSurface_SetCookie,
    SteamAPI_ISteamHTMLSurface_SetPageScaleFactor,
    SteamAPI_ISteamHTMLSurface_AllowStartRequest,
    SteamAPI_ISteamHTMLSurface_JSDialogResponse,
    SteamAPI_ISteamHTMLSurface_FileLoadDialogResponse,
};

static void *vtable_ISteamHTMLSurface003[] = {
    SteamAPI_ISteamHTMLSurface_Init,
    SteamAPI_ISteamHTMLSurface_Shutdown,
    SteamAPI_ISteamHTMLSurface_CreateBrowser,
    SteamAPI_ISteamHTMLSurface_RemoveBrowser,
    SteamAPI_ISteamHTMLSurface_LoadURL,
    SteamAPI_ISteamHTMLSurface_SetSize,
    SteamAPI_ISteamHTMLSurface_StopLoad,
    SteamAPI_ISteamHTMLSurface_Reload,
    SteamAPI_ISteamHTMLSurface_GoBack,
    SteamAPI_ISteamHTMLSurface_GoForward,
    SteamAPI_ISteamHTMLSurface_AddHeader,
    SteamAPI_ISteamHTMLSurface_ExecuteJavascript,
    SteamAPI_ISteamHTMLSurface_MouseUp,
    SteamAPI_ISteamHTMLSurface_MouseDown,
    SteamAPI_ISteamHTMLSurface_MouseDoubleClick,
    SteamAPI_ISteamHTMLSurface_MouseMove,
    SteamAPI_ISteamHTMLSurface_MouseWheel,
    SteamAPI_ISteamHTMLSurface_KeyDown,
    SteamAPI_ISteamHTMLSurface_KeyUp,
    SteamAPI_ISteamHTMLSurface_KeyChar,
    SteamAPI_ISteamHTMLSurface_SetHorizontalScroll,
    SteamAPI_ISteamHTMLSurface_SetVerticalScroll,
    SteamAPI_ISteamHTMLSurface_SetKeyFocus,
    SteamAPI_ISteamHTMLSurface_ViewSource,
    SteamAPI_ISteamHTMLSurface_CopyToClipboard,
    SteamAPI_ISteamHTMLSurface_PasteFromClipboard,
    SteamAPI_ISteamHTMLSurface_Find,
    SteamAPI_ISteamHTMLSurface_StopFind,
    SteamAPI_ISteamHTMLSurface_GetLinkAtPosition,
    SteamAPI_ISteamHTMLSurface_SetCookie,
    SteamAPI_ISteamHTMLSurface_SetPageScaleFactor,
    SteamAPI_ISteamHTMLSurface_SetBackgroundMode,
    SteamAPI_ISteamHTMLSurface_AllowStartRequest,
    SteamAPI_ISteamHTMLSurface_JSDialogResponse,
    SteamAPI_ISteamHTMLSurface_FileLoadDialogResponse,
};

static void *vtable_ISteamHTMLSurface004[] = {
    SteamAPI_ISteamHTMLSurface_Init,
    SteamAPI_ISteamHTMLSurface_Shutdown,
    SteamAPI_ISteamHTMLSurface_CreateBrowser,
    SteamAPI_ISteamHTMLSurface_RemoveBrowser,
    SteamAPI_ISteamHTMLSurface_LoadURL,
    SteamAPI_ISteamHTMLSurface_SetSize,
    SteamAPI_ISteamHTMLSurface_StopLoad,
    SteamAPI_ISteamHTMLSurface_Reload,
    SteamAPI_ISteamHTMLSurface_GoBack,
    SteamAPI_ISteamHTMLSurface_GoForward,
    SteamAPI_ISteamHTMLSurface_AddHeader,
    SteamAPI_ISteamHTMLSurface_ExecuteJavascript,
    SteamAPI_ISteamHTMLSurface_MouseUp,
    SteamAPI_ISteamHTMLSurface_MouseDown,
    SteamAPI_ISteamHTMLSurface_MouseDoubleClick,
    SteamAPI_ISteamHTMLSurface_MouseMove,
    SteamAPI_ISteamHTMLSurface_MouseWheel,
    SteamAPI_ISteamHTMLSurface_KeyDown,
    SteamAPI_ISteamHTMLSurface_KeyUp,
    SteamAPI_ISteamHTMLSurface_KeyChar,
    SteamAPI_ISteamHTMLSurface_SetHorizontalScroll,
    SteamAPI_ISteamHTMLSurface_SetVerticalScroll,
    SteamAPI_ISteamHTMLSurface_SetKeyFocus,
    SteamAPI_ISteamHTMLSurface_ViewSource,
    SteamAPI_ISteamHTMLSurface_CopyToClipboard,
    SteamAPI_ISteamHTMLSurface_PasteFromClipboard,
    SteamAPI_ISteamHTMLSurface_Find,
    SteamAPI_ISteamHTMLSurface_StopFind,
    SteamAPI_ISteamHTMLSurface_GetLinkAtPosition,
    SteamAPI_ISteamHTMLSurface_SetCookie,
    SteamAPI_ISteamHTMLSurface_SetPageScaleFactor,
    SteamAPI_ISteamHTMLSurface_SetBackgroundMode,
    SteamAPI_ISteamHTMLSurface_SetDPIScalingFactor,
    SteamAPI_ISteamHTMLSurface_AllowStartRequest,
    SteamAPI_ISteamHTMLSurface_JSDialogResponse,
    SteamAPI_ISteamHTMLSurface_FileLoadDialogResponse,
};

static void *vtable_ISteamHTMLSurface005[] = {
    SteamAPI_ISteamHTMLSurface_Init,
    SteamAPI_ISteamHTMLSurface_Shutdown,
    SteamAPI_ISteamHTMLSurface_CreateBrowser,
    SteamAPI_ISteamHTMLSurface_RemoveBrowser,
    SteamAPI_ISteamHTMLSurface_LoadURL,
    SteamAPI_ISteamHTMLSurface_SetSize,
    SteamAPI_ISteamHTMLSurface_StopLoad,
    SteamAPI_ISteamHTMLSurface_Reload,
    SteamAPI_ISteamHTMLSurface_GoBack,
    SteamAPI_ISteamHTMLSurface_GoForward,
    SteamAPI_ISteamHTMLSurface_AddHeader,
    SteamAPI_ISteamHTMLSurface_ExecuteJavascript,
    SteamAPI_ISteamHTMLSurface_MouseUp,
    SteamAPI_ISteamHTMLSurface_MouseDown,
    SteamAPI_ISteamHTMLSurface_MouseDoubleClick,
    SteamAPI_ISteamHTMLSurface_MouseMove,
    SteamAPI_ISteamHTMLSurface_MouseWheel,
    SteamAPI_ISteamHTMLSurface_KeyDown,
    SteamAPI_ISteamHTMLSurface_KeyUp,
    SteamAPI_ISteamHTMLSurface_KeyChar,
    SteamAPI_ISteamHTMLSurface_SetHorizontalScroll,
    SteamAPI_ISteamHTMLSurface_SetVerticalScroll,
    SteamAPI_ISteamHTMLSurface_SetKeyFocus,
    SteamAPI_ISteamHTMLSurface_ViewSource,
    SteamAPI_ISteamHTMLSurface_CopyToClipboard,
    SteamAPI_ISteamHTMLSurface_PasteFromClipboard,
    SteamAPI_ISteamHTMLSurface_Find,
    SteamAPI_ISteamHTMLSurface_StopFind,
    SteamAPI_ISteamHTMLSurface_GetLinkAtPosition,
    SteamAPI_ISteamHTMLSurface_SetCookie,
    SteamAPI_ISteamHTMLSurface_SetPageScaleFactor,
    SteamAPI_ISteamHTMLSurface_SetBackgroundMode,
    SteamAPI_ISteamHTMLSurface_SetDPIScalingFactor,
    SteamAPI_ISteamHTMLSurface_OpenDeveloperTools,
    SteamAPI_ISteamHTMLSurface_AllowStartRequest,
    SteamAPI_ISteamHTMLSurface_JSDialogResponse,
    SteamAPI_ISteamHTMLSurface_FileLoadDialogResponse,
};

VtableEntry vtable_ISteamHTMLSurface[] = {
    {2, vtable_ISteamHTMLSurface002, sizeof(vtable_ISteamHTMLSurface002), 0},
    {3, vtable_ISteamHTMLSurface003, sizeof(vtable_ISteamHTMLSurface003), 0},
    {4, vtable_ISteamHTMLSurface004, sizeof(vtable_ISteamHTMLSurface004), 0},
    {5, vtable_ISteamHTMLSurface005, sizeof(vtable_ISteamHTMLSurface005), 0},
    {0, NULL, 0, 0},
};
