#include "steam.h"

static void *vtable_ISteamClient012[] = {
    SteamAPI_ISteamClient_CreateSteamPipe,
    SteamAPI_ISteamClient_BReleaseSteamPipe,
    SteamAPI_ISteamClient_ConnectToGlobalUser,
    SteamAPI_ISteamClient_CreateLocalUser,
    SteamAPI_ISteamClient_ReleaseUser,
    SteamAPI_ISteamClient_GetISteamUser,
    SteamAPI_ISteamClient_GetISteamGameServer,
    SteamAPI_ISteamClient_SetLocalIPBindingUint32,
    SteamAPI_ISteamClient_GetISteamFriends,
    SteamAPI_ISteamClient_GetISteamUtils,
    SteamAPI_ISteamClient_GetISteamMatchmaking,
    SteamAPI_ISteamClient_GetISteamMatchmakingServers,
    SteamAPI_ISteamClient_GetISteamGenericInterface,
    SteamAPI_ISteamClient_GetISteamUserStats,
    SteamAPI_ISteamClient_GetISteamGameServerStats,
    SteamAPI_ISteamClient_GetISteamApps,
    SteamAPI_ISteamClient_GetISteamNetworking,
    SteamAPI_ISteamClient_GetISteamRemoteStorage,
    SteamAPI_ISteamClient_GetISteamScreenshots,
    SteamAPI_ISteamClient_RunFrame,
    SteamAPI_ISteamClient_GetIPCCallCount,
    SteamAPI_ISteamClient_SetWarningMessageHook,
    SteamAPI_ISteamClient_BShutdownIfAllPipesClosed,
    SteamAPI_ISteamClient_GetISteamHTTP,
    SteamAPI_ISteamClient_GetISteamUnifiedMessages,
    SteamAPI_ISteamClient_GetISteamController,
    SteamAPI_ISteamClient_GetISteamUGC,
};

static void *vtable_ISteamClient017[] = {
    SteamAPI_ISteamClient_CreateSteamPipe,
    SteamAPI_ISteamClient_BReleaseSteamPipe,
    SteamAPI_ISteamClient_ConnectToGlobalUser,
    SteamAPI_ISteamClient_CreateLocalUser,
    SteamAPI_ISteamClient_ReleaseUser,
    SteamAPI_ISteamClient_GetISteamUser,
    SteamAPI_ISteamClient_GetISteamGameServer,
    SteamAPI_ISteamClient_SetLocalIPBindingUint32,
    SteamAPI_ISteamClient_GetISteamFriends,
    SteamAPI_ISteamClient_GetISteamUtils,
    SteamAPI_ISteamClient_GetISteamMatchmaking,
    SteamAPI_ISteamClient_GetISteamMatchmakingServers,
    SteamAPI_ISteamClient_GetISteamGenericInterface,
    SteamAPI_ISteamClient_GetISteamUserStats,
    SteamAPI_ISteamClient_GetISteamGameServerStats,
    SteamAPI_ISteamClient_GetISteamApps,
    SteamAPI_ISteamClient_GetISteamNetworking,
    SteamAPI_ISteamClient_GetISteamRemoteStorage,
    SteamAPI_ISteamClient_GetISteamScreenshots,
    SteamAPI_ISteamClient_RunFrame, // private
    SteamAPI_ISteamClient_GetIPCCallCount,
    SteamAPI_ISteamClient_SetWarningMessageHook,
    SteamAPI_ISteamClient_BShutdownIfAllPipesClosed,
    SteamAPI_ISteamClient_GetISteamHTTP,
    SteamAPI_ISteamClient_GetISteamUnifiedMessages,
    SteamAPI_ISteamClient_GetISteamController,
    SteamAPI_ISteamClient_GetISteamUGC,
    SteamAPI_ISteamClient_GetISteamAppList,
    SteamAPI_ISteamClient_GetISteamMusic,
    SteamAPI_ISteamClient_GetISteamMusicRemote,
    SteamAPI_ISteamClient_GetISteamHTMLSurface,
    SteamAPI_ISteamClient_Set_SteamAPI_CPostAPIResultInProcess,           // private
    SteamAPI_ISteamClient_Remove_SteamAPI_CPostAPIResultInProcess,        // private
    SteamAPI_ISteamClient_Set_SteamAPI_CCheckCallbackRegisteredInProcess, // private
    SteamAPI_ISteamClient_GetISteamInventory,
    SteamAPI_ISteamClient_GetISteamVideo,
    SteamAPI_ISteamClient_GetISteamParentalSettings,
};

static void *vtable_ISteamClient020[] = {
    SteamAPI_ISteamClient_CreateSteamPipe,
    SteamAPI_ISteamClient_BReleaseSteamPipe,
    SteamAPI_ISteamClient_ConnectToGlobalUser,
    SteamAPI_ISteamClient_CreateLocalUser,
    SteamAPI_ISteamClient_ReleaseUser,
    SteamAPI_ISteamClient_GetISteamUser,
    SteamAPI_ISteamClient_GetISteamGameServer,
    SteamAPI_ISteamClient_SetLocalIPBinding,
    SteamAPI_ISteamClient_GetISteamFriends,
    SteamAPI_ISteamClient_GetISteamUtils,
    SteamAPI_ISteamClient_GetISteamMatchmaking,
    SteamAPI_ISteamClient_GetISteamMatchmakingServers,
    SteamAPI_ISteamClient_GetISteamGenericInterface,
    SteamAPI_ISteamClient_GetISteamUserStats,
    SteamAPI_ISteamClient_GetISteamGameServerStats,
    SteamAPI_ISteamClient_GetISteamApps,
    SteamAPI_ISteamClient_GetISteamNetworking,
    SteamAPI_ISteamClient_GetISteamRemoteStorage,
    SteamAPI_ISteamClient_GetISteamScreenshots,
    SteamAPI_ISteamClient_GetISteamGameSearch,
    SteamAPI_ISteamClient_RunFrame, // private
    SteamAPI_ISteamClient_GetIPCCallCount,
    SteamAPI_ISteamClient_SetWarningMessageHook,
    SteamAPI_ISteamClient_BShutdownIfAllPipesClosed,
    SteamAPI_ISteamClient_GetISteamHTTP,
    SteamAPI_ISteamClient_GetISteamUnifiedMessages,
    SteamAPI_ISteamClient_GetISteamController,
    SteamAPI_ISteamClient_GetISteamUGC,
    SteamAPI_ISteamClient_GetISteamAppList,
    SteamAPI_ISteamClient_GetISteamMusic,
    SteamAPI_ISteamClient_GetISteamMusicRemote,
    SteamAPI_ISteamClient_GetISteamHTMLSurface,
    SteamAPI_ISteamClient_Set_SteamAPI_CPostAPIResultInProcess,           // private
    SteamAPI_ISteamClient_Remove_SteamAPI_CPostAPIResultInProcess,        // private
    SteamAPI_ISteamClient_Set_SteamAPI_CCheckCallbackRegisteredInProcess, // private
    SteamAPI_ISteamClient_GetISteamInventory,
    SteamAPI_ISteamClient_GetISteamVideo,
    SteamAPI_ISteamClient_GetISteamParentalSettings,
    SteamAPI_ISteamClient_GetISteamInput,
    SteamAPI_ISteamClient_GetISteamParties,
    SteamAPI_ISteamClient_GetISteamRemotePlay,
    SteamAPI_ISteamClient_DestroyAllInterfaces, // private
};

VtableEntry vtable_ISteamClient[] = {
    {12, vtable_ISteamClient012, sizeof(vtable_ISteamClient012), 0},
    {17, vtable_ISteamClient017, sizeof(vtable_ISteamClient017), VTABLE_HAS_PRIVATE},
    {20, vtable_ISteamClient020, sizeof(vtable_ISteamClient020), VTABLE_HAS_PRIVATE},
    {0, NULL, 0, 0},
};
